### ISSUE TITLE
Error while deploying platform for the first time

### ISSUE THREAD

**Issue by santteegt** [Jasig/SSP-Platform#1]
When running `SSP_CONFIGDIR=/usr/local/ssp/ssp-local ant -Dmaven.test.skip=true clean initportal`, the following exception is being thrown:

```
[java] -------------------------------------------------------------------
     [java] GMS: address=ee0cd82bf263-29993, cluster=uPortal.cacheManager, physical address=172.17.0.2:38999
     [java] -------------------------------------------------------------------
     [java] INFO  [24:37.861] Initializing ExecutorService  'uPortalTaskScheduler'
     [java] INFO  [24:40.549] Building JPA container EntityManagerFactory for persistence unit 'RawEventsDb'
     [java] WARN  [24:41.447] HHH000342: Could not obtain connection to query metadata : The connection attempt failed.
     [java] INFO  [24:41.468] Shutting down ExecutorService 'uPortalTaskScheduler'
     [java] Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'messageSource' defined in class path resource [properties/contexts/mvcContext.xml]: Cannot create inner bean 'org.jasig.portal.i18n.DatabaseMessageSource#442675e1' of type [org.jasig.portal.i18n.DatabaseMessageSource] while setting bean property 'parentMessageSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.jasig.portal.i18n.DatabaseMessageSource#442675e1': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.jasig.portal.i18n.DatabaseMessageSource.setMessageDao(org.jasig.portal.i18n.dao.IMessageDao); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMessageDao': Injection of persistence dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'RawEventsDbEntityManagerFactory' defined in class path resource [properties/contexts/eventPersistenceContext.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: RawEventsDb] Unable to build EntityManagerFactory
     [java] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:287)
     [java] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:122)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1417)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1158)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
     [java] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:198)
     [java] 	at org.springframework.context.support.AbstractApplicationContext.initMessageSource(AbstractApplicationContext.java:786)
     [java] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:467)
     [java] 	at org.jasig.portal.spring.PortalApplicationContextLocator$PortalApplicationContextCreator.createSingleton(PortalApplicationContextLocator.java:189)
     [java] 	at org.jasig.portal.spring.PortalApplicationContextLocator$PortalApplicationContextCreator.createSingleton(PortalApplicationContextLocator.java:171)
     [java] 	at org.jasig.portal.utils.threading.SingletonDoubleCheckedCreator.create(SingletonDoubleCheckedCreator.java:55)
     [java] 	at org.jasig.portal.utils.threading.DoubleCheckedCreator.get(DoubleCheckedCreator.java:111)
     [java] 	at org.jasig.portal.spring.PortalApplicationContextLocator.getApplicationContext(PortalApplicationContextLocator.java:146)
     [java] 	at org.jasig.portal.spring.locator.PortalDbLocator.getPortalDb(PortalDbLocator.java:45)
     [java] 	at org.jasig.portal.RDBMServices.getDataSource(RDBMServices.java:139)
     [java] 	at org.jasig.portal.RDBMServices.getConnection(RDBMServices.java:191)
     [java] 	at org.jasig.portal.RDBMServices.getConnection(RDBMServices.java:174)
     [java] 	at org.jasig.portal.tools.DbTest.main(DbTest.java:41)
     [java] Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.jasig.portal.i18n.DatabaseMessageSource#442675e1': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.jasig.portal.i18n.DatabaseMessageSource.setMessageDao(org.jasig.portal.i18n.dao.IMessageDao); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMessageDao': Injection of persistence dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'RawEventsDbEntityManagerFactory' defined in class path resource [properties/contexts/eventPersistenceContext.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: RawEventsDb] Unable to build EntityManagerFactory
     [java] 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:289)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1146)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
     [java] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:276)
     [java] 	... 21 more
     [java] Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.jasig.portal.i18n.DatabaseMessageSource.setMessageDao(org.jasig.portal.i18n.dao.IMessageDao); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMessageDao': Injection of persistence dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'RawEventsDbEntityManagerFactory' defined in class path resource [properties/contexts/eventPersistenceContext.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: RawEventsDb] Unable to build EntityManagerFactory
     [java] 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:604)
     [java] 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
     [java] 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:286)
     [java] 	... 25 more
     [java] Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMessageDao': Injection of persistence dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'RawEventsDbEntityManagerFactory' defined in class path resource [properties/contexts/eventPersistenceContext.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: RawEventsDb] Unable to build EntityManagerFactory
     [java] 	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.postProcessPropertyValues(PersistenceAnnotationBeanPostProcessor.java:344)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1146)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
     [java] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:917)
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:860)
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:775)
     [java] 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
     [java] 	... 27 more
     [java] Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'RawEventsDbEntityManagerFactory' defined in class path resource [properties/contexts/eventPersistenceContext.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: RawEventsDb] Unable to build EntityManagerFactory
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1512)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
     [java] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
     [java] 	at org.springframework.orm.jpa.EntityManagerFactoryUtils.findEntityManagerFactory(EntityManagerFactoryUtils.java:101)
     [java] 	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.findNamedEntityManagerFactory(PersistenceAnnotationBeanPostProcessor.java:515)
     [java] 	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.findEntityManagerFactory(PersistenceAnnotationBeanPostProcessor.java:497)
     [java] 	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor$PersistenceElement.resolveEntityManager(PersistenceAnnotationBeanPostProcessor.java:663)
     [java] 	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor$PersistenceElement.getResourceToInject(PersistenceAnnotationBeanPostProcessor.java:634)
     [java] 	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:164)
     [java] 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
     [java] 	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.postProcessPropertyValues(PersistenceAnnotationBeanPostProcessor.java:341)
     [java] 	... 38 more
     [java] Caused by: javax.persistence.PersistenceException: [PersistenceUnit: RawEventsDb] Unable to build EntityManagerFactory
     [java] 	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:915)
     [java] 	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:890)
     [java] 	at org.hibernate.ejb.HibernatePersistence.createContainerEntityManagerFactory(HibernatePersistence.java:74)
     [java] 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:290)
     [java] 	at org.jasig.portal.jpa.EventingLocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(EventingLocalContainerEntityManagerFactoryBean.java:61)
     [java] 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:310)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1571)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1509)
     [java] 	... 52 more
     [java] Caused by: org.hibernate.HibernateException: Connection cannot be null when 'hibernate.dialect' not set
     [java] 	at org.hibernate.service.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:97)
     [java] 	at org.hibernate.service.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:67)
     [java] 	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:170)
     [java] 	at org.hibernate.service.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:75)
     [java] 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:159)
     [java] 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:131)
     [java] 	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:73)
     [java] 	at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2279)
     [java] 	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2275)
     [java] 	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1744)
     [java] 	at org.hibernate.ejb.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:94)
     [java] 	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:905)
     [java] 	... 59 more
```

I set the corresponding the database properties in the `ssp-platform-config.properties` as follows

```
environment.build.hibernate.connection.driver_class=org.postgresql.Driver
environment.build.hibernate.connection.url=jdbc:postgresql://localhost:5432/ssp
environment.build.hibernate.connection.username=sspadmin
environment.build.hibernate.connection.password=sspadmin
environment.build.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
```

What could be the problem? 

Thank for your help

**Comment by ChristianMurphy** [comment]
Hey @santteegt :wave: 
The [SSP User mailing list](https://groups.google.com/a/apereo.org/forum/#!forum/ssp-user) and/or the [uPortal User mailing list](https://groups.google.com/a/apereo.org/forum/#!forum/uportal-user) is probably the best place to reach out with this question.
